### ISSUE TITLE
Error: 404 - undefined

### ISSUE THREAD

**Issue by bezoerb** [bezoerb/gulp-php2html#6]
```
Error: 404 - undefined
    at Server.<anonymous> (mypathtophp2html/index.js:160:10)
    at Server.g (events.js:180:16)
    at Server.EventEmitter.emit (events.js:92:17)
    at net.js:1273:10
    at process._tickCallback (node.js:415:13)
```

**Comment by bezoerb** [comment]
@cortopy 
could you share your task config?

**Comment by cortopy** [comment]
I never understood how this works to be honest. As I see it, php would have to be interpreted before it can be converted, so that's what I don't get. That's why I was never able to use gulp html nodes before.

Dest directory is populated with all the right folders so php2htlml is definitely accessing the right source path, but subfolders in dest folder are all empty after running task.

My gulp config is this:

```
gulp.task('php', function() {
     gulp.src("path/to/files/**/*")
       .pipe(php2html())
       .pipe(gulp.dest("/myPathtoDest"));
});
```

**Comment by bezoerb** [comment]
this module uses `php-cgi` under the hood to convert php files. Have you checked you have `php-cgi` [installed](https://github.com/bezoerb/gulp-php2html/blob/master/README.md#installing-php-cgi) and available in your PATH?
You can check this by running `php-cgi --version`

**Comment by bezoerb** [comment]
I'll see if a can set up some test project soon so i can try to reproduce and fix the error.
Which operating system are you using?

**Comment by cortopy** [comment]
Thanks a lot for that @bezoerb 

My php-cgi version is `PHP 5.5.12-2ubuntu4.3 (cgi-fcgi)`
I'm using Ubuntu 14.10 and the PHP project in question is based on Magento

**Comment by bezoerb** [comment]
Magento uses rewrites so you need to configure a router. (Available since this morning ;))
I've hacked together a simple working example with a fresh magento installation.
Folder structure:
```shell
├── gulpfile.js
├── node_modules
├── static
│   └── GENERATED HTML
├── htdocs (magento root)
│   ├── .htaccess
│   ├── index.php
│   ├── app
....
```

gulpfile
```js
'use strict';
var gulp = require('gulp');
var php2html = require('gulp-php2html');

gulp.task('php',function(){
    php2html.routes(['/index.php/customer-service'])
        .pipe(php2html({baseDir:'htdocs', router: 'htdocs/index.php'}))
        .pipe(gulp.dest('static/'));
});
```

unfortunately it's not very comfortable to add all routes manually but maybe you could generate the array manually from the magento sitemap?

**Comment by cortopy** [comment]
That makes sense. I currently do that for uncss anyway. I was just trying to get bypassed that, but it was a good try. Thanks for the explanation
