### ISSUE TITLE
Unhandled stream error in pipe.

### ISSUE THREAD

**Issue by MateuszWilk** [bezoerb/gulp-php2html#8]
I'm getting this error after running gulp php2html:

`stream.js:74
throw er; // Unhandled stream error in pipe.
^
Error: 204 - No Content
    at Server.<anonymous> (node_modules/php2html/index.js:165:10)
    at Server.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at Server.emit (events.js:179:7)
    at emitCloseNT (net.js:1523:8)
    at nextTickCallbackWith1Arg (node.js:463:9)
    at process._tickCallback (node.js:385:17)`

while my gulp task looks like this:

`gulp.task('php2html', function(){
	return gulp.src("./src/*.php")
		.pipe(php2html())
        .pipe(gulp.dest("./test"))
        .pipe(print());
});`

Someone maybe had such issue and was able to resolve it?

I'm on:
- node v.5.5.0
- gulp 3.9.1

**Comment by bezoerb** [comment]
do you have [`php-cgi`](https://github.com/bezoerb/gulp-php2html#installing-php-cgi) installed and in your PATH? 
You check by typing `php-cgi -v`

**Comment by MateuszWilk** [comment]
`PHP 5.6.17 (cgi-fcgi) (built: Jan  8 2016 10:27:56)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with XCache v3.2.0, Copyright (c) 2005-2014, by mOo
    with XCache Cacher v3.2.0, Copyright (c) 2005-2014, by mOo`

**Comment by bezoerb** [comment]
Looks good. 
I'll see if i can reproduce the error this evening.

**Comment by bezoerb** [comment]
the plugin throws an error when there's no content generated for a file.
You could either handle the error:
```js
var gutil = require('gulp-util');
var php2html = require('gulp-php2html');
gulp.task('php2html', function(){ 
    return gulp.src("./src/*.php") 
        .pipe(php2html().on('error',gutil.log)) 
        .pipe(gulp.dest("./test")) 
        .pipe(print()); 
})
```

or use [`gulp-plumber`](https://github.com/floatdrop/gulp-plumber)
```js
var plumber = require('gulp-plumber');
var php2html = require('gulp-php2html');
gulp.task('php2html', function(){ 
    return gulp.src("./src/*.php") 
        .pipe(plumber())
        .pipe(php2html()) 
        .pipe(gulp.dest("./test")) 
        .pipe(print()); 
})
```

**Comment by bezoerb** [comment]
I'll add an option to make the fail on error optional

**Comment by bezoerb** [comment]
@MateuszWilk or you can disable the new option `haltOnError` which just got introduced in [v0.3.0](https://github.com/bezoerb/gulp-php2html/releases/tag/v0.3.0)

**Comment by MateuszWilk** [comment]
Hi, now its working as expected, without even changing anything in my `gulp task`.
One thing i noticed is You probably removed by accident the dependency for `stream-array` which, right after update, screamed for missing module. Thanks for the quick fix and upgrade!!
